on: workflow_dispatch
jobs:
  allure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout gh pages
        uses: actions/checkout@v3
        with:
          path: gh-pages
          ref: gh-pages
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run maven tests
        run: |
          mvn --batch-mode test
      - name: Generate allure report
        run: |
          mvn allure:report
      - name: Generate gh page
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history